name: github-release
on:
  workflow_call:
    secrets:
      GH_ORG_TOKEN:
        required: true
    
jobs:

  github-release:
    name: Github Release
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: write

    steps:

    - name: downcase REPO
      run: |
        echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
    # - name: use REPO
    #   run: echo "The value of REPO is: ${{ env.REPO }}"

    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Version
      id: version
      uses: paulhatch/semantic-version@v4.0.3
      with:
        major_pattern: "BREAKING CHANGE"
        minor_pattern: "feat:"
        bump_each_commit: true

    - name: Build Changelog
      id: changelog
      uses: mikepenz/release-changelog-builder-action@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_ORG_TOKEN }}
        branch: ${{ steps.version.outputs.version_tag }}
        tags: true

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.version.outputs.version_tag }}
        generate_release_notes: true
        body: ${{steps.changelog.outputs.changelog}}