name: gitops-promote-version-bump

on:
  workflow_call:
    inputs:
      environment_repository:
        type: string
        required: true
      pull_request:
        type: boolean
        required: false
    secrets:
      GH_ORG_TOKEN:
        required: true

jobs:

  gitops-promote-version-bump:
    name: GitOps Promote Version Bump
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
    - name: Checkout production environment
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.environment_repository }}
        persist-credentials: false
        fetch-depth: 0

    # - name: Create PR branch
    #   if: inputs.pull_request
    #   run: |
    #     git checkout -b promote/${{ github.event.repository.name }}-${{ github.ref_name }}

    - name: Update prod environment
      uses: mikefarah/yq@master
      with:
        cmd: yq -i '.spec.source.targetRevision = "${{ github.ref_name }}"' helm/templates/${{ github.event.repository.name }}.yaml

    - name: Commit Prod Env Changes
      run: |
        if output=$(git status --porcelain) && [ -z "$output" ]; then
          # Working directory clean

          echo "No changes to commit"
        else 
          # Uncommitted changes

          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"   
          git add -A
          git commit -m "feat(${{ github.event.repository.name }}): Promoting ${{ github.event.repository.name }} to ${{ github.ref_name }}"
        fi

    - name: Push main
      if: inputs.pull_request == false
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_ORG_TOKEN }}
        repository: ${{ inputs.environment_repository }}
    
    # - name: Push branch
    #   if: inputs.pull_request
    #   uses: ad-m/github-push-action@master
    #   with:
    #     github_token: ${{ secrets.GH_ORG_TOKEN }}
    #     repository: ${{ inputs.environment_repository }}
    #     branch: promote/${{ github.event.repository.name }}-${{ github.ref_name }}

    - name: Create Pull Request
      if: inputs.pull_request
      uses: peter-evans/create-pull-request@v4
      with:
        branch: promote/${{ github.event.repository.name }}-${{ github.ref_name }}